### ISSUE TITLE
builder.setCwd failes to start process

### ISSUE THREAD

**Issue by jpork** [brettwooldridge/NuProcess#110]
I use version 2.0.0 with OpenJdk-13 on linux. When setting the cwd with:
`builder.setCwd(cwd) `
the process start fails and the test hangs.
When commenting out the cwd setting everything is fine.

The cwd is an absolute path to an existing directory with write access. 

```
Mar 31, 2020 11:20:52 PM com.zaxxer.nuprocess.linux.LinuxProcess start
WARNING: Failed to start process
java.io.IOException: error=2, No such file or directory
	at com.zaxxer.nuprocess.internal.LibJava10.Java_java_lang_ProcessImpl_forkAndExec(Native Method)
	at com.zaxxer.nuprocess.linux.LinuxProcess.prepareProcess(LinuxProcess.java:149)
	at com.zaxxer.nuprocess.linux.LinuxProcess.start(LinuxProcess.java:66)
	at com.zaxxer.nuprocess.linux.LinProcessFactory.createProcess(LinProcessFactory.java:40)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:259)
	at ur.urwerk.process.Execute$Context.$anonfun$execute$2(Execute.scala:84)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by jpork** [comment]
cannot reproduce.
