### ISSUE TITLE
Underlying processes complete but waitFor times out (OSX)

### ISSUE THREAD

**Issue by edalquist** [brettwooldridge/NuProcess#25]
I have an app that runs lots and lots of processes via a thread pool. Fairly consistently after running for ~30 minutes my calls to waitFor start hanging, stuck on the CountDownLatch. There are no nuprocess threads running and the underlying processes are all done.

I'm wondering if `exitPending.countDown();` in `BasePosixProcess.onExit` should be moved into a finally block to ensure it is called if onExit is called.

```
"pool-1-thread-7" #18 prio=5 os_prio=31 tid=0x00007fca9307a000 nid=0x6303 waiting on condition [0x0000000126611000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076ab28ed8> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at com.zaxxer.nuprocess.internal.BasePosixProcess.waitFor(BasePosixProcess.java:151)
	at org.dalquist.photos.survey.PhotoHashingRunner$MetaDataExtractor.call(PhotoHashingRunner.java:277)
	at org.dalquist.photos.survey.PhotoHashingRunner$MetaDataExtractor.call(PhotoHashingRunner.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000006c7d88990> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

**Comment by edalquist** [comment]
I added some logging and am seeing the following:

```
21:46:21.976 [ProcessKqueue3] ERROR com.zaxxer.nuprocess.osx.OsxProcess onExit - Failed during onExit
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98) ~[na:1.8.0_40]
	at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312) ~[na:1.8.0_40]
	at com.zaxxer.nuprocess.osx.ProcessKqueue.closeStdin(ProcessKqueue.java:116) [classes/:na]
	at com.zaxxer.nuprocess.osx.ProcessKqueue.closeStdin(ProcessKqueue.java:32) [classes/:na]
	at com.zaxxer.nuprocess.internal.BasePosixProcess.closeStdin(BasePosixProcess.java:187) ~[classes/:na]
	at com.zaxxer.nuprocess.internal.BasePosixProcess.onExit(BasePosixProcess.java:343) ~[classes/:na]
	at com.zaxxer.nuprocess.osx.ProcessKqueue.process(ProcessKqueue.java:177) [classes/:na]
	at com.zaxxer.nuprocess.internal.BaseEventProcessor.run(BaseEventProcessor.java:73) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

I'll dig more and see why the queue is not getting cleared.

**Comment by edalquist** [comment]
So it appears ProcessKqueue.checkStdinCloses() is never called on OSX for me.

**Comment by brettwooldridge** [comment]
Can you test with the latest version, 1.0.0?

**Comment by edalquist** [comment]
Will do, I'll have a chance to test this weekend.

**Comment by brettwooldridge** [comment]
@edalquist Things moving fast :dash:  ... version 1.0.3, please.

**Comment by edalquist** [comment]
Didn't have a chance to test this weekend and I won't for a few weeks. Feel free to close this issue and I'll re-open it if I still have problems.

**Comment by brettwooldridge** [comment]
@edalquist Closed pending re-test.
