### ISSUE TITLE
Unit test fails on Mac OS X Yosemite (10.10.5)

### ISSUE THREAD

**Issue by pfxuan** [brettwooldridge/NuProcess#45]
It looks like current version can not pass `noExecutableFound()` test on Mac OS:

```java
/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java "-Dmaven.home=/Applications/IntelliJ IDEA 14.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA 14.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" -Didea.launcher.port=7534 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA 14.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.4.jar:/Applications/IntelliJ IDEA 14.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=14.1.4 test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building NuProcess 1.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ nuprocess ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ nuprocess ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/user/project/Java/NuProcess/upstream/NuProcess/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ nuprocess ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 33 source files to /Users/user/project/Java/NuProcess/upstream/NuProcess/target/classes
[WARNING] /Users/user/project/Java/NuProcess/upstream/NuProcess/src/main/java/com/zaxxer/nuprocess/internal/UnsafeHelper.java:[23,16] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /Users/user/project/Java/NuProcess/upstream/NuProcess/src/main/java/com/zaxxer/nuprocess/internal/UnsafeHelper.java:[28,25] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /Users/user/project/Java/NuProcess/upstream/NuProcess/src/main/java/com/zaxxer/nuprocess/internal/UnsafeHelper.java:[34,20] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /Users/user/project/Java/NuProcess/upstream/NuProcess/src/main/java/com/zaxxer/nuprocess/internal/UnsafeHelper.java:[36,20] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[WARNING] /Users/user/project/Java/NuProcess/upstream/NuProcess/src/main/java/com/zaxxer/nuprocess/internal/UnsafeHelper.java:[56,18] sun.misc.Unsafe is internal proprietary API and may be removed in a future release
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ nuprocess ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/user/project/Java/NuProcess/upstream/NuProcess/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ nuprocess ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /Users/user/project/Java/NuProcess/upstream/NuProcess/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ nuprocess ---
[INFO] Surefire report directory: /Users/user/project/Java/NuProcess/upstream/NuProcess/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.zaxxer.nuprocess.CatTest
Starting test lotOfProcesses()
 Iteration 1
 Iteration 2
 Iteration 3
 Iteration 4
 Iteration 5
 Iteration 6
 Iteration 7
 Iteration 8
 Iteration 9
 Iteration 10
 Iteration 11
 Iteration 12
 Iteration 13
 Iteration 14
 Iteration 15
 Iteration 16
 Iteration 17
 Iteration 18
 Iteration 19
 Iteration 20
Completed test lotOfProcesses()
Starting test decodingShortUtf8Data()
Completed test decodingShortUtf8Data()
Starting test badExit()
Completed test badExit()
Starting test lotOfData()
Completed test lotOfData()
Starting test decodingLongUtf8Data()
Completed test decodingLongUtf8Data()
Starting test noExecutableFound()
java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 2
	at com.zaxxer.nuprocess.internal.BasePosixProcess.checkReturnCode(BasePosixProcess.java:867)
	at com.zaxxer.nuprocess.internal.BasePosixProcess.start(BasePosixProcess.java:359)
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at com.zaxxer.nuprocess.CatTest.noExecutableFound(CatTest.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Completed test noExecutableFound()
Starting test changeCwd() (java cwd=/Users/user/project/Java/NuProcess/upstream/NuProcess, tmp=/var/folders/2m/qc6sw15x5bx0d71kqs9vm2xh0000gp/T/junit6815590441566501432)
Completed test changeCwd()
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.748 sec - in com.zaxxer.nuprocess.CatTest
Running com.zaxxer.nuprocess.FastExitingProcessTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.zaxxer.nuprocess.FastExitingProcessTest
Running com.zaxxer.nuprocess.InterruptTest
```

**Comment by pfxuan** [comment]
However,  I still can go through the rest of unit tests after about 100 secs delay:  

```java
Running com.zaxxer.nuprocess.InterruptTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 101.629 sec - in com.zaxxer.nuprocess.InterruptTest
Starting threadTest1()
  started thread: 0
  started thread: 1
Running com.zaxxer.nuprocess.ThreadedTest
  started thread: 2
  started thread: 3
0 Maximum memory used: -188653352
0 Total execution time (ms): 9070
2 Maximum memory used: -195108624
2 Total execution time (ms): 9492
1 Maximum memory used: -229829072
1 Total execution time (ms): 9625
3 Maximum memory used: -244092816
3 Total execution time (ms): 9832
Completed threadTest1()
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.834 sec - in com.zaxxer.nuprocess.ThreadedTest

Results :

Tests run: 13, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:58.428s
[INFO] Finished at: Mon Sep 21 11:55:25 EDT 2015
[INFO] Final Memory: 11M/160M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```

**Comment by brettwooldridge** [comment]
@pfxuan If you're referring to the stacktrace printed by that test, that is normal (and the expected result).  However, it should not be delaying so long.  On my Mac, running against the current *master* branch (1.0.4-SNAPSHOT), the build completes without error in ~20 seconds:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.016 s
[INFO] Finished at: 2015-09-22T12:41:06+09:00
[INFO] Final Memory: 28M/327M
[INFO] ------------------------------------------------------------------------
```

**Comment by pfxuan** [comment]
@brettwooldridge It seems https://github.com/brettwooldridge/NuProcess/pull/42 solves the problem. The running time of unit tests on Mac is reduced to about 17s after pulling the last four commits. Thank you for your help! 

```java
Results :

Tests run: 14, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.418s
[INFO] Finished at: Tue Sep 22 01:58:49 EDT 2015
[INFO] Final Memory: 17M/228M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```
