### ISSUE TITLE
CreateProcessW() failed, error: 2

### ISSUE THREAD

**Issue by hyee** [brettwooldridge/NuProcess#54]
Hello,

I'm experiencing following error when I try to test the example in your page except replacing `/bin/cat` as `cmd.exe`:

    java.lang.RuntimeException: CreateProcessW() failed, error: 2
            at com.zaxxer.nuprocess.windows.WindowsProcess.start(WindowsProcess.java:262)
            at com.zaxxer.nuprocess.windows.WinProcessFactory.createProcess(WinProcessFactory.java:42)
            at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)

The problem is: 1) No idea of what `error 2` means; 2) The `start()` function only prints the error message, instead of throwing the error.

I have included `jna-4.2.1.jar` and `jna-platform-4.2.1.jar` into the classpath, and also try to extract the dll of JNA into the library path, but the error is still there.

**Comment by hyee** [comment]
Sorry, I notice that I have set the wrong cwd, case is closed. Thanks.
