### ISSUE TITLE
Upgrading to 1.2.x (from 1.1.3) causes NoClassDefFoundError in macOS (and Java 10)

### ISSUE THREAD

**Issue by robby-phd** [brettwooldridge/NuProcess#87]
Upgrading to 1.2.*x* throws the following exception when using NuProcess in macOS (10.13.4, Zulu JDK 10.2+3-jdk10.0.1):

```
java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.nuprocess.osx.OsxProcess
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:33)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at org.sireum.util.jvm.Exec.run(Exec.scala:100)
        ...
```

Steps to reproduce using 1.2.2 (note: this first downloads Zulu JDK, Sbt, and other dependencies):

```bash
git clone --recursive --depth=1 https://github.com/sireum/v3 sireum-v3
sed -i.bak 's/nuprocess=1.1.3/nuprocess=1.2.2/' sireum-v3/versions.properties
sireum-v3/bin/sbt-launch.sh "project logika-jvm" test
```

**Comment by robby-phd** [comment]
Thanks.  I can confirm that 1.2.2 on Linux with Zulu JDK 10 crashes:

```bash
java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.nuprocess.internal.LibC
	at com.zaxxer.nuprocess.internal.BasePosixProcess.createPipes(BasePosixProcess.java:585)
	at com.zaxxer.nuprocess.linux.LinuxProcess.start(LinuxProcess.java:86)
	at com.zaxxer.nuprocess.linux.LinProcessFactory.createProcess(LinProcessFactory.java:40)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at org.sireum.util.jvm.Exec.run(Exec.scala:100)
```

1.1.3 on Linux with the Zulu JDK works; 1.2.2 on Linux with Oracle Java 8 also works.

**Comment by brettwooldridge** [comment]
@robby-phd NuProcess v1.2.3 has been published with support for Azul Systems' Zulu JVM.

**Comment by robby-phd** [comment]
Great, thanks!
